name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ParseTodos:
    name: Parse Todo comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4
